### ISSUE TITLE
Why is it deprecated?

### ISSUE THREAD

**Issue by mrchief** [catberry/catberry-es6#1]
No reason or explanation given as to why it is deprecated, nor what the way forward is.

**Comment by pragmader** [comment]
Because new versions of Catberry (starting with [8.0.0](https://github.com/catberry/catberry/releases/tag/8.0.0)) are using ES6/2015 by default, no need to have any plugin like this.

**Comment by pragmader** [comment]
Also, I'm pretty sure if you try to install this package using NPM it will output a warning with the explanation that I gave to you.

**Comment by mrchief** [comment]
So if I were to use `import`, `async/await`, etc in my code, it'd just work?

**Comment by pragmader** [comment]
Everything you have in Node.js on server works out of the box and builds into a ES5 bundle for browsers.
Depends on the version of Node you use. AFIK, new modules are not supported by Node yet.

**Comment by mrchief** [comment]
Write. Which is why you need the evil monster called babel to do the transpilation. So a way to specify that would be cool.

**Comment by pragmader** [comment]
If want to transpile the code for the server and run it in node it makes no sense to me at all. Yes, Node does not support a couple of new JavaScript features but transpile the whole source code because of it is very inefficient. If we had the same JavaScript support in all browsers I would remove Babel completely from the framework. Catberry will not have Babel for the server environment, if you want that please consider other libraries because it does not fit your needs.

**Comment by mrchief** [comment]
> but transpile the whole source code because of it is very inefficient. 

Why would you transpile parts of code when **all** your code uses those new constructs? 

> Catberry will not have Babel for the server environment, if you want that please consider other libraries because it does not fit your needs.

Hmmm, ok. I respect your choice. I'll look elsewhere. Feels bad since this library seemed to be the best implementation (amongst those using morphdom) and an un-opinionated and lighter alternative to React. In the end, it seems to me this library is just as much opinionated as React/Angular.
